name: Changesets

on:
  push:
    branches: ["main"]

permissions: {} # No permissions needed as we use a PAT. Make sure the PAT has the proper permissions. See below.

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          # `persist-credentials: false` is important not only for security reasons
          # but also to ensure that `git push --follow-tags` run by the Changesets action in the later step
          # don't use the default GITHUB_TOKEN, which doesn't trigger other workflows such as the release workflow.
          # Ref: https://github.com/orgs/community/discussions/26220
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.CHANGESETS_APP_ID }}
          private-key: ${{ secrets.CHANGESETS_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Create Release Pull Request or Tag
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          publish: npm run changeset:release
        env:
          # PRs created using `GITHUB_TOKEN` doesn't trigger CI workflows, so we need to use a PAT or app token.
          # - The PAT should be fine-grained and its permissions are properly configured (R/W for Contents and Pull Requests).
          # - The app token should be generated using a GitHub App that has proper permissions (R/W for Contents and Pull Requests).
          # Ref: https://github.com/orgs/community/discussions/55906
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          # GITHUB_TOKEN: ${{ secrets.CHANGESETS_PAT }}
